theme: jekyll-theme-minimal
title: Tomas Bencomo
description: My future description here
logo: https://github.com/tjbencomo/tjbencomo.github.io/blob/master/Bencomo_Tomas_J_18JU.JPG?raw=true
show_downloads: "false"
